name: CI/CD - Refresh EC2 via ASG

on:
  push:
    branches:
      - main  # change if your default branch is not 'main'

jobs:
  refresh-asg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start Instance Refresh on ASG
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name diagnexus-auto-scaling-group \
            --strategy Rolling \
            --preferences '{"MinHealthyPercentage": 100, "InstanceWarmup": 300}'
